### ISSUE TITLE
Stickers Link no Longer works on Footer

### ISSUE THREAD

**Issue by shemszot** [phonegap/book#9]
The "Stickers" Link no longer works since it used to go to a StickerMule marketplace location which is now defunct.  I created a new Fork which suggest linking to an active StickerYou location which has the phonegap stickers on it's marketplace:

https://github.com/shemszot/book/commit/86cad4529c6dc078aaf77cf30decfeab26003c54

Link to marketplace:
https://www.stickeryou.com/products/phonegap/802

**Comment by purplecabbage** [comment]
Lots of things will stop working now ...
